### ISSUE TITLE
Executable doesn't run on Windows

### ISSUE THREAD

**Issue by dblock** [dbgrandi/claide-plugins#4]
See https://github.com/danger/danger/pull/544 or https://ci.appveyor.com/project/orta/danger/build/1.0.918.

```
     NotImplementedError:
       fork() function is unimplemented on this machine
     # ./lib/danger/commands/plugins/plugin_gem.rb:64:in `block in clone_template'
     # ./lib/danger/commands/plugins/plugin_gem.rb:61:in `clone_template'
     # ./lib/danger/commands/plugins/plugin_gem.rb:42:in `run'
     # ./spec/lib/danger/commands/plugins/plugin_gem_spec.rb:15:in `block (2 levels) in <module:Danger
```

**Comment by manicmaniac** [comment]
https://github.com/danger/danger/issues/1480 looks related to this issue.

```
[!] using template 'https://github.com/danger/danger-plugin-template'
[!] The exception involves the following plugins:
 -  claide-plugins

C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-plugins-0.9.2/lib/claide/executable.rb:51:in ``': No such file or directory - which git (Errno::ENOENT)
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-plugins-0.9.2/lib/claide/executable.rb:51:in `execute_command'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-plugins-0.9.2/lib/claide/executable.rb:27:in `block in executable'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-plugins-0.9.2/lib/claide/command/template_runner.rb:23:in `block in clone_template'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/cork-0.3.0/lib/cork/board.rb:184:in `section'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-plugins-0.9.2/lib/claide/command/template_runner.rb:20:in `clone_template'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-plugins-0.9.2/lib/claide/command/plugins/create.rb:51:in `run'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from C:/Users/<username>/.local/share/gem/ruby/3.2.0/gems/danger-9.4.2/bin/danger:5:in `<top (required)>'
        from C:/Users/<username>/AppData/Local/Microsoft/WindowsApps/danger:25:in `load'
        from C:/Users/<username>/AppData/Local/Microsoft/WindowsApps/danger:25:in `<main>'
```
